---
- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: copy telegraf conf
  template:
    src: telegraf.conf.j2
    dest: "/etc/telegraf/telegraf.conf"
    owner: root
    group: root
  notify: restart telegraf
  when: telegraf_conf_use_template

- name: start and enable telegraf
  service: name=telegraf state=started enabled=yes
