---
- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Create Telegraf config dir.
  file: path={{ telegraf_config_dir }} state=directory
  when: telegraf_config_use_template

- name: Copy Telegraf config.
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_config_dir }}/telegraf.conf"
    owner: root
    group: root
  notify: restart telegraf
  when: telegraf_config_use_template

- name: Start and enable Telegraf.
  service: name=telegraf state=started enabled=yes
