# See https://hub.docker.com/_/debian/
FROM debian:jessie

# Systemd integration
ENV CONTAINER docker

# Systemd integration
RUN (cd /lib/systemd/system/sysinit.target.wants/; \
for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*; \
rm -f /etc/systemd/system/*.wants/*; \
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*; \
rm -f /lib/systemd/system/anaconda.target.wants/*;

# Update package list
RUN apt-get update; \
# Install SSH server
apt-get install -y openssh-server ca-certificates python; \
# Remove cached data
apt-get clean all;

# "Missing privilege separation directory" error
RUN mkdir /run/sshd; \
# Create root SSH dir
mkdir /root/.ssh;

# Authenticate ssh user
ADD id_rsa.pub /root/.ssh/authorized_keys

# Listen on port 22
EXPOSE 22

# Systemd integration
VOLUME ["/sys/fs/cgroup", "/run"]

# Systemd integration
CMD ["/lib/systemd/systemd"]
