# See https://hub.docker.com/_/centos/
FROM centos:7

# Systemd integration
ENV CONTAINER docker

# Systemd integration
RUN (cd /lib/systemd/system/sysinit.target.wants/; \
for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*; \
rm -f /etc/systemd/system/*.wants/*; \
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*; \
rm -f /lib/systemd/system/anaconda.target.wants/*;

# Update metadata cache
RUN yum makecache; \
# Install SSH server
yum install -y openssh-server; \
# Remove cached data
yum clean all;

# Create root SSH dir
RUN mkdir /root/.ssh;

# Authenticate ssh user
ADD id_rsa.pub /root/.ssh/authorized_keys

# Listen on port 22
EXPOSE 22

# Systemd integration
VOLUME ["/sys/fs/cgroup"]

# Systemd integration
CMD ["/usr/sbin/init"]
